"""A read-only viewer for the contents of `generated_user_rules.py`.

This module provides a ComfyUI node that allows users to view the contents of
their generated metadata rules file. This is useful for debugging and
understanding how the metadata is being captured.
"""

import logging
import os

logger = logging.getLogger(__name__)


class ShowGeneratedUserRules:
    """A node to expose the generated Python rules file as a STRING output.

    This class implements a ComfyUI node that reads the `generated_user_rules.py`
    file and outputs its contents as a string. This allows users to inspect
    the rules that have been generated by the `MetadataRuleScanner` and saved
    with the `SaveGeneratedUserRules` node.
    """

    @classmethod
    def INPUT_TYPES(cls):  # noqa: N802
        """Define the input types for the `ShowGeneratedUserRules` node.

        This node does not have any inputs, as it only reads a file from disk.

        Returns:
            dict: An empty dictionary for the `required` inputs.
        """
        return {"required": {}}

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("generated_user_rules.py",)
    FUNCTION = "show_rules"
    CATEGORY = "SaveImageWithMetaDataUniversal/rules"
    DESCRIPTION = "Display the contents of generated_user_rules.py for review or editing."

    def _rules_path(self) -> str:
        """Construct the absolute path to `generated_user_rules.py`.

        This method determines the full path to the `generated_user_rules.py`
        file, which is located in the `defs/ext` directory of the package.

        Returns:
            str: The absolute path to the `generated_user_rules.py` file.
        """
        base_py = os.path.dirname(os.path.dirname(__file__))  # .../py
        return os.path.join(base_py, "defs", "ext", "generated_user_rules.py")

    def show_rules(self) -> tuple[str]:
        """Read the contents of the generated rules file.

        This method opens and reads the `generated_user_rules.py` file, and
        returns its contents as a string. If the file does not exist or an
        error occurs during reading, it returns an empty string or an error
        message.

        Returns:
            tuple[str]: A tuple containing the contents of the rules file.
        """
        path = self._rules_path()
        if not os.path.exists(path):
            return ("",)
        try:
            with open(path, encoding="utf-8") as f:
                content = f.read()
        except OSError as e:
            logger.warning("[Metadata Rules] I/O error reading %s: %s", path, e)
            return (f"Error reading generated_user_rules.py: {e}",)
        return (content,)
