import re
import pytest
from typing import Sequence, Iterable

from saveimage_unimeta.defs.meta import MetaField
from saveimage_unimeta.capture import Capture

# The environment variable METADATA_TEST_MODE changes
# various aspects of the production codes (as well as tests)
# in ComfyUI_SaveImageWithMetaDataUniversal.
# One of its effects is to change the format of strings
# generated by Capture.gen_parameters_str().
# This fixture temporarily disables it, so that a test can
# validate what string the function will generate
# in the production environment.
@pytest.fixture()
def disable_test_mode(monkeypatch):
    """pytest fixture to force METADATA_TEST_MODE='' during a test."""
    monkeypatch.setenv("METADATA_TEST_MODE", "")

def _parametrize_with_id(argnames: str | Sequence[str], argvalues: Iterable[Sequence[object]]):
    """Customized pytest.mark.parametrize to use complex data in parameters.

    This is a custom decorator for parametrized pytest tests
    that use some complex data in test parameters easily.
    It automatically makes the first item in each param tuple
    an id of that param tuple,
    so that the argvalues values are more legible
    (because the first item in a tuple is more prominent than the last)
    as well as test outputs.

    You can use the first item only as an id,
    or you can actually use it in the test.

    Args:
        argnames: argument names exactly as in pytest.mark.parametrize.
        argvalues: arguments values represented as an iterable of sequences,
            usually a list of tuples of argument values.

    Returns:
        A function that decorates a test method in a similar way as
        pytest.mark.parametrize,
        except that each argument values tuple is given an id
        based on the first argument value in the tuple.

    Examples:

        @_parametrize(
            "x, y",
            [
                ("case1", {'case1': 'value1', 'exception': 'case1'})
            ]
        )

        is equivalent to

        @pytest.mark.parametrize(
            "x, y",
            [
                pytest.param("case1", {'case1': 'value1', 'exception': 'case1'}, id="case1")
            ]
        )
    """
    return pytest.mark.parametrize(
        argnames,
        [pytest.param(*param, id=str(param[0])) for param in argvalues]
    )

# Various stub data for the arguments called "inputs"

# "inputs" that contains no LoRA references.
_inputs0 = {
    MetaField.MODEL_NAME: [('n1', 'model.safetensors', 2)],
    MetaField.MODEL_HASH: [('n1', '1111111111', 2)],

    MetaField.POSITIVE_PROMPT: [('n2', '1girl', 1)],
    MetaField.NEGATIVE_PROMPT: [('n3', 'nsfw', 1)],

    MetaField.SEED: [('n4', 0, 0)],
    MetaField.STEPS: [('n4', 30, 0)],
    MetaField.CFG: [('n4', 4.0, 0)],
    MetaField.SAMPLER_NAME: [('n4', 'euler', 0)],
    MetaField.SCHEDULER: [('n4', 'normal', 0)],
}

# "inputs" that contains one LoRA reference.
_inputs1 = {
    **_inputs0,
    MetaField.LORA_MODEL_NAME: [('n5', 'lora-5.safetensors', 1)],
    MetaField.LORA_MODEL_HASH: [('n5', '5555555555', 1)],
    MetaField.LORA_STRENGTH_MODEL: [('n5', 0.9, 1)],
    MetaField.LORA_STRENGTH_CLIP: [('n5', 0.7, 1)],
}

# "inputs" that contains two LoRA references.
_inputs2 = {
    **_inputs0,
    MetaField.LORA_MODEL_NAME: [
        ('n5', 'lora-5.safetensors', 1),
        ('n6', 'lora-6.safetensors', 1)
    ],
    MetaField.LORA_MODEL_HASH: [
        ('n5', '5555555555', 1),
        ('n6', '6666666666', 1),
    ],
    MetaField.LORA_STRENGTH_MODEL: [
        ('n5', 0.9, 1),
        ('n6', 0.8, 1),
    ],
    MetaField.LORA_STRENGTH_CLIP: [
        ('n5', 0.7, 1),
        ('n5', 0.6, 1),
    ],
}

_inputs = {
    "inputs0": _inputs0,
    "inputs1": _inputs1,
    "inputs2": _inputs2,
}

class TestGenPnginfoDict:

    @_parametrize_with_id(
        "inputs_name, lora_hashes",
        [
            ("inputs0", None),
            ("inputs1", '"lora-5: 5555555555"'),
            ("inputs2", '"lora-5: 5555555555, lora-6: 6666666666"'),
        ]
    )
    def test_gen_pnginfo_dict_creates_lora_hashes(self, inputs_name, lora_hashes):
        inputs = {**_inputs[inputs_name]}
        pnginfo = Capture.gen_pnginfo_dict(inputs, inputs, True)
        assert pnginfo.get("Lora hashes") == lora_hashes

    @_parametrize_with_id(
        "inputs_name, lora_strengths",
        [
            ("inputs0", None),
            ("inputs1", '<lora:lora-5:0.9>'),
            ("inputs2", '<lora:lora-5:0.9> <lora:lora-6:0.8>'),
        ]
    )
    def test_gen_pnginfo_dict_creates_lora_strengths(self, inputs_name, lora_strengths):
        inputs = {**_inputs[inputs_name]}
        pnginfo = Capture.gen_pnginfo_dict(inputs, inputs, True)
        assert pnginfo.get("Lora strengths") == lora_strengths

    @_parametrize_with_id(
        "inputs_name, positive_prompt",
        [
            # Unlike earlier versions, gen_pnginfo_dict never changes "Positive prompt".
            ("inputs0", "1girl"),
            ("inputs1", "1girl"),
            ("inputs2", "1girl"),
        ]
    )
    def test_gen_pnginfo_dict_does_not_create_lora_designations_in_positive_prompt(self, inputs_name, positive_prompt):
        inputs = {**_inputs[inputs_name]}
        pnginfo = Capture.gen_pnginfo_dict(inputs, inputs, True)
        assert pnginfo.get("Positive prompt") == positive_prompt

@pytest.mark.usefixtures("disable_test_mode")
class TestGenParametersStr:

    # Civitai uses a single regular expression to find a LoRA designation
    # and Hypernetwork designation.
    # This is the same regular expression as Civitai
    # with "hypernet:" reference removed.
    LORA_DESIGNATION_RE = '<lora:[a-zA-Z0-9_.-]+:[0-9.]+>'

    @_parametrize_with_id(
        "inputs_name, lora_hashes",
        [
            ("inputs0", []),
            ("inputs1", ['"lora-5: 5555555555"']),
            ("inputs2", ['"lora-5: 5555555555, lora-6: 6666666666"']),
        ]
    )
    def test_gen_parameters_str_creates_lora_hashes_if_lora_strengths_in_prompt_is_true(
            self, inputs_name, lora_hashes):
        inputs = {**_inputs[inputs_name]}
        pnginfo = Capture.gen_pnginfo_dict(inputs, inputs, True)
        parameters = Capture.gen_parameters_str(pnginfo, lora_strengths_in_prompt=True)
        # "Steps:" comes first in the _other_ metadata.
        # "Lora hashes:" should be somewhere after it.
        p = parameters.find('Steps:')
        assert p >= 0, "'Steps:' not found"
        found = re.findall(', *Lora hashes: *("[^"]*") *(?:,|$)', parameters[p:])
        assert found == lora_hashes

    @_parametrize_with_id(
        "inputs_name, lora_hashes",
        [
            ("inputs0", []),
            ("inputs1", []),
            ("inputs2", []),
        ]
    )
    def test_gen_parameters_str_does_not_create_lora_hashes_if_lora_strengths_in_prompt_is_false(
            self, inputs_name, lora_hashes):
        inputs = {**_inputs[inputs_name]}
        pnginfo = Capture.gen_pnginfo_dict(inputs, inputs, True)
        parameters = Capture.gen_parameters_str(pnginfo, lora_strengths_in_prompt=False)
        found = re.findall(', *Lora hashes: *("[^"]*") *(?:,|$)', parameters)
        assert found == lora_hashes

    @_parametrize_with_id(
        "inputs_name, lora_strengths_in_prompt, lora_designations",
        [
            ("inputs0", False, []),
            ("inputs0", True,  []),
            ("inputs1", False, []),
            ("inputs1", True,  ["<lora:lora-5:0.9>"]),
            ("inputs2", False, []),
            ("inputs2", True,  ["<lora:lora-5:0.9>", "<lora:lora-6:0.8>"]),
        ]
    )
    def test_gen_parameters_str_creates_lora_designations_in_positive_prompt_depending_on_lora_strengths_in_prompt(
            self, inputs_name, lora_strengths_in_prompt, lora_designations):
        inputs = {**_inputs[inputs_name]}
        pnginfo = Capture.gen_pnginfo_dict(inputs, inputs, True)
        parameters = Capture.gen_parameters_str(pnginfo, lora_strengths_in_prompt=lora_strengths_in_prompt)
        # "Negative prompt:" terminates the positive prompt text.
        p = parameters.find('Negative prompt:')
        assert p >= 0, "'Negative prompt:' not found"
        found = re.findall(self.LORA_DESIGNATION_RE, parameters[:p])
        assert found == lora_designations

    @pytest.mark.parametrize(
        "inputs_name",
        [
            ("inputs0"),
            ("inputs1"),
            ("inputs2"),
        ]
    )
    def test_gen_parameters_str_does_not_create_lora_designations_if_no_positive_prompt(
            self, inputs_name):
        inputs = {**_inputs[inputs_name]}
        del inputs[MetaField.POSITIVE_PROMPT]
        pnginfo = Capture.gen_pnginfo_dict(inputs, inputs, True)
        parameters = Capture.gen_parameters_str(pnginfo, lora_strengths_in_prompt=True)
        found = re.findall(self.LORA_DESIGNATION_RE, parameters)
        assert not found
        assert parameters.startswith("Negative prompt")

    @_parametrize_with_id(
        "inputs_name, lora_strengths_in_prompt",
        [
            ("inputs0", False),
            ("inputs0", True),
            ("inputs1", False),
            ("inputs1", True),
            ("inputs2", False),
            ("inputs2", True),
        ]
    )
    def test_gen_parameters_str_never_leaves_lora_strengths_metadata(
            self, inputs_name, lora_strengths_in_prompt):
        inputs = {**_inputs[inputs_name]}
        pnginfo = Capture.gen_pnginfo_dict(inputs, inputs, True)
        parameters = Capture.gen_parameters_str(pnginfo, lora_strengths_in_prompt=lora_strengths_in_prompt)
        found = re.findall(', *Lora strengths:', parameters)
        assert not found
